"""
Health Report Generator Module
========================================
Generates professional, personalized health reports for Health Companion platform.
Converts user inputs, calculated metrics, and ML predictions into clinical-style reports.

Author: Health Companion Platform
Date: 2026
"""

from datetime import datetime
sep = '='*80
from enum import Enum

class RiskLevel(Enum):
    """Risk classification levels"""
    LOW = "Low Risk"
    MODERATE = "Moderate Risk"
    HIGH = "High Risk"

class ReportType(Enum):
    """Types of health reports"""
    CARDIOVASCULAR = "Cardiovascular Risk Assessment"
    DIABETES = "Diabetes Risk Assessment"
    STROKE = "Stroke Risk Assessment"
    BMI = "Body Mass Index Assessment"


class HealthReportGenerator:
    """
    Professional health report generator for Health Companion platform.
    Generates clinical-style reports suitable for PDF export.
    """
    
    PLATFORM_NAME = "Health Companion"
    DISCLAIMER_TEXT = """
IMPORTANT MEDICAL DISCLAIMER:
This health report is generated by the Health Companion platform using AI-based risk 
analysis algorithms and is intended for informational purposes only. It is NOT a 
substitute for professional medical advice, diagnosis, or treatment from a qualified 
healthcare provider. 

Please consult with a licensed physician, cardiologist, endocrinologist, or other 
appropriate medical specialist for:
- Confirmation of any health risks identified in this report
- Personalized medical advice
- Treatment planning and management
- Any health concerns or medical conditions

The Health Companion platform and its developers assume no responsibility for any 
medical decisions made based on this report.
    """
    
    def __init__(self):
        """Initialize the report generator"""
        self.report_date = datetime.now().strftime("%d %B %Y")
    
    def generate_cardiovascular_report(self, patient_data, risk_prediction):
        """
        Generate a cardiovascular risk assessment report.
        
        Args:
            patient_data (dict): Dictionary containing:
                - name (str): Patient name
                - age (int): Age in years
                - gender (str): Gender (Male/Female)
                - height (float): Height in cm
                - weight (float): Weight in kg
                - bmi (float): Calculated BMI
                - bmi_category (str): BMI category (Underweight/Normal/Overweight/Obese)
                - systolic_bp (int): Systolic blood pressure
                - diastolic_bp (int): Diastolic blood pressure
                - bp_category (str): BP category (Normal/Elevated/Stage 1/Stage 2)
                - cholesterol (int): Cholesterol level (1=Normal, 2=Above Normal, 3=Well Above Normal)
                - glucose (int): Glucose level (1=Normal, 2=Above Normal)
                - smoking (int): Smoking status (0=Non-smoker, 1=Smoker)
                - alcohol (int): Alcohol consumption (0=No, 1=Yes)
                - physical_activity (int): Physical activity (0=No, 1=Yes)
            
            risk_prediction (dict): Dictionary containing:
                - risk_level (str): "Low Risk", "Moderate Risk", or "High Risk"
                - probability (float): Risk probability (0-1)
                - recommendation (str): Clinical recommendation
        
        Returns:
            str: Formatted professional health report
        """
        metrics = {
            "Age": f"{patient_data.get('age', 'N/A')} years",
            "BMI": f"{patient_data.get('bmi', 0):.1f} ({patient_data.get('bmi_category', 'N/A')})",
            "Blood Pressure": f"{patient_data.get('systolic_bp', 'N/A')}/{patient_data.get('diastolic_bp', 'N/A')} mmHg",
            "BP Category": patient_data.get('bp_category', 'N/A'),
            "Cholesterol": self._decode_cholesterol(patient_data.get('cholesterol', 1)),
            "Glucose": self._decode_glucose(patient_data.get('glucose', 1))
        }
        findings = self._build_cardio_findings(patient_data)
        actions = self._build_cardio_actions(patient_data, risk_prediction)
        return self._generate_structured_report("Cardiovascular Risk Assessment", patient_data, risk_prediction, metrics, findings, actions)
    
    def generate_diabetes_report(self, patient_data, risk_prediction):
        """
        Generate a diabetes risk assessment report.
        
        Args:
            patient_data (dict): Dictionary containing:
                - name (str): Patient name
                - age (int): Age in years
                - gender (str): Gender (Male/Female)
                - pregnancies (int): Number of pregnancies (for females)
                - weight (float): Weight in kg
                - height (float): Height in cm
                - bmi (float): Calculated BMI
                - bmi_category (str): BMI category
                - glucose (float): Fasting glucose level (mg/dL)
                - blood_pressure (float): Blood pressure (mmHg)
                - insulin (float): Insulin level (µU/ml)
                - skin_thickness (float): Triceps skin fold thickness (mm)
                - diabetes_pedigree_function (float): Diabetes pedigree score
            
            risk_prediction (dict): Dictionary containing:
                - risk_level (str): "Low Risk", "Moderate Risk", or "High Risk"
                - probability (float): Risk probability (0-1)
                - recommendation (str): Clinical recommendation
        
        Returns:
            str: Formatted professional health report
        """
        metrics = {
            "Age": f"{patient_data.get('age', 'N/A')} years",
            "BMI": f"{patient_data.get('bmi', 0):.1f} ({patient_data.get('bmi_category', 'N/A')})",
            "Fasting Glucose": f"{patient_data.get('glucose', 'N/A')} mg/dL",
            "Blood Pressure": f"{patient_data.get('blood_pressure', 'N/A')} mmHg",
            "Insulin": f"{patient_data.get('insulin', 'N/A')} µU/ml",
            "Family History Score": f"{patient_data.get('diabetes_pedigree_function', 0):.3f}"
        }
        findings = self._build_diabetes_findings(patient_data)
        actions = self._build_diabetes_actions(patient_data, risk_prediction)
        return self._generate_structured_report("Diabetes Risk Assessment", patient_data, risk_prediction, metrics, findings, actions)
    
    def generate_stroke_report(self, patient_data, risk_prediction):
        """
        Generate a stroke risk assessment report.
        
        Args:
            patient_data (dict): Dictionary containing:
                - name (str): Patient name
                - age (int): Age in years
                - gender (str): Gender (Male/Female)
                - height (float): Height in cm
                - weight (float): Weight in kg
                - bmi (float): Calculated BMI
                - bmi_category (str): BMI category
                - hypertension (int): History of hypertension (0=No, 1=Yes)
                - heart_disease (int): History of heart disease (0=No, 1=Yes)
                - avg_glucose (float): Average glucose level
                - smoking_status (int): Smoking status (0-3 scale)
                - ever_married (int): Marital status (0=No, 1=Yes)
                - work_type (str): Type of work
                - residence_type (str): Urban/Rural
            
            risk_prediction (dict): Dictionary containing:
                - risk_level (str): "Low Risk", "Moderate Risk", or "High Risk"
                - probability (float): Risk probability (0-1)
                - recommendation (str): Clinical recommendation
        
        Returns:
            str: Formatted professional health report
        """
        metrics = {
            "Age": f"{patient_data.get('age', 'N/A')} years",
            "BMI": f"{patient_data.get('bmi', 0):.1f} ({patient_data.get('bmi_category', 'N/A')})",
            "Average Glucose": f"{patient_data.get('avg_glucose', 'N/A')} mg/dL",
            "Hypertension": "Yes" if patient_data.get('hypertension') == 1 else "No",
            "Heart Disease": "Yes" if patient_data.get('heart_disease') == 1 else "No",
            "Smoking Status": self._decode_smoking_status(patient_data.get('smoking_status', 0))
        }
        findings = self._build_stroke_findings(patient_data)
        actions = self._build_stroke_actions(patient_data, risk_prediction)
        return self._generate_structured_report("Stroke Risk Assessment", patient_data, risk_prediction, metrics, findings, actions)

    def _generate_structured_report(self, report_title, patient_data, risk_prediction, metrics, findings, actions):
        """Generate concise structured report shared by all prediction modules."""
        probability = float(risk_prediction.get('probability', 0) or 0)
        risk_level = risk_prediction.get('risk_level', 'Unknown')
        patient_name = patient_data.get('name', 'Patient')
        risk_band = self._risk_band(probability)

        report = []
        report.append(f"{self.PLATFORM_NAME} | {report_title}")
        report.append(f"Date: {self.report_date}")
        report.append(f"Patient: {patient_name}")
        report.append("-" * 72)

        report.append("1) Risk Summary")
        report.append(f"- Predicted Risk: {risk_level} ({probability*100:.1f}%)")
        report.append(f"- Priority: {risk_band}")
        report.append("")

        report.append("2) Key Clinical Inputs")
        for key, value in metrics.items():
            report.append(f"- {key}: {value}")
        report.append("")

        report.append("3) Main Findings")
        for item in self._unique_keep_order(findings)[:6]:
            report.append(f"- {item}")
        report.append("")

        report.append("4) Action Plan")
        for item in self._unique_keep_order(actions)[:8]:
            report.append(f"- {item}")
        report.append("")

        report.append("5) Guidance")
        report.append("- This is an AI-supported risk estimate, not a final medical diagnosis.")
        report.append("- Review this report with a qualified clinician for confirmation and care planning.")
        report.append("- Repeat assessment after profile updates or major lifestyle/health changes.")
        report.append("-" * 72)

        return "\n".join(report)

    @staticmethod
    def _unique_keep_order(items):
        seen = set()
        unique = []
        for item in items:
            normalized = " ".join(str(item).strip().lower().split())
            if normalized and normalized not in seen:
                seen.add(normalized)
                unique.append(str(item).strip())
        return unique

    @staticmethod
    def _risk_band(probability):
        if probability >= 0.7:
            return "High - consult specialist soon"
        if probability >= 0.4:
            return "Moderate - begin focused prevention"
        return "Low - maintain healthy habits"

    def _build_cardio_findings(self, patient_data):
        findings = []
        bmi_cat = str(patient_data.get('bmi_category', '')).lower()
        bp_cat = str(patient_data.get('bp_category', '')).lower()
        if "obese" in bmi_cat or "overweight" in bmi_cat:
            findings.append("Body weight is above recommended range and contributes to cardiovascular risk.")
        else:
            findings.append("Body weight is currently in a favorable range for cardiovascular health.")
        if "stage 2" in bp_cat or "stage 1" in bp_cat or "elevated" in bp_cat:
            findings.append("Blood pressure is above normal and is a major cardiovascular risk driver.")
        else:
            findings.append("Blood pressure appears within normal limits.")
        if patient_data.get('smoking') == 1:
            findings.append("Smoking status increases vascular and cardiac risk.")
        if patient_data.get('physical_activity') == 0:
            findings.append("Low physical activity is increasing baseline risk.")
        return findings

    def _build_cardio_actions(self, patient_data, risk_prediction):
        probability = float(risk_prediction.get('probability', 0) or 0)
        actions = []
        if probability >= 0.7:
            actions.append("Book a cardiology consultation within 1-2 weeks.")
        elif probability >= 0.4:
            actions.append("Plan a primary care review and cardiovascular screening soon.")
        actions.extend([
            "Target at least 150 minutes/week of moderate aerobic activity.",
            "Adopt a low-sodium, high-fiber, heart-focused diet.",
            "Monitor blood pressure at home and keep a weekly log."
        ])
        if patient_data.get('smoking') == 1:
            actions.append("Start a smoking cessation plan with clinical support.")
        if patient_data.get('alcohol') == 1:
            actions.append("Reduce alcohol intake to guideline limits.")
        return actions

    def _build_diabetes_findings(self, patient_data):
        findings = []
        glucose = float(patient_data.get('glucose', 0) or 0)
        bmi_cat = str(patient_data.get('bmi_category', '')).lower()
        dpf = float(patient_data.get('diabetes_pedigree_function', 0) or 0)
        if glucose >= 126:
            findings.append("Fasting glucose is in diabetic range and requires confirmation testing.")
        elif glucose >= 100:
            findings.append("Fasting glucose suggests prediabetes and early intervention is important.")
        else:
            findings.append("Fasting glucose is within normal range.")
        if "obese" in bmi_cat or "overweight" in bmi_cat:
            findings.append("Current BMI category contributes to insulin resistance risk.")
        if dpf >= 0.8:
            findings.append("Family history score indicates elevated inherited diabetes risk.")
        insulin = float(patient_data.get('insulin', 0) or 0)
        if insulin > 12:
            findings.append("Insulin level suggests possible insulin resistance.")
        return findings

    def _build_diabetes_actions(self, patient_data, risk_prediction):
        probability = float(risk_prediction.get('probability', 0) or 0)
        actions = []
        if probability >= 0.7:
            actions.append("Schedule an endocrinology consultation and HbA1c test soon.")
        elif probability >= 0.4:
            actions.append("Arrange fasting glucose/HbA1c follow-up with your physician.")
        actions.extend([
            "Reduce refined carbohydrates and sweetened drinks.",
            "Increase daily movement and structured exercise.",
            "Track fasting glucose trend and body weight regularly."
        ])
        if str(patient_data.get('bmi_category', '')).lower() in ("overweight", "obese"):
            actions.append("Aim for gradual weight reduction (5-10% initial target).")
        return actions

    def _build_stroke_findings(self, patient_data):
        findings = []
        age = int(patient_data.get('age', 0) or 0)
        glucose = float(patient_data.get('avg_glucose', 0) or 0)
        if patient_data.get('hypertension') == 1:
            findings.append("Hypertension is present and strongly associated with stroke risk.")
        else:
            findings.append("No hypertension history reported.")
        if patient_data.get('heart_disease') == 1:
            findings.append("Heart disease history adds additional stroke risk.")
        if age >= 50:
            findings.append("Age group places you in a higher baseline stroke-risk category.")
        if glucose >= 126:
            findings.append("Glucose profile is elevated and may increase cerebrovascular risk.")
        if patient_data.get('smoking_status') in (2, 3):
            findings.append("Current smoking behavior increases stroke risk.")
        return findings

    def _build_stroke_actions(self, patient_data, risk_prediction):
        probability = float(risk_prediction.get('probability', 0) or 0)
        actions = []
        if probability >= 0.7:
            actions.append("Seek neurology/physician review promptly for stroke prevention planning.")
        elif probability >= 0.4:
            actions.append("Review blood pressure and vascular risk factors with your physician.")
        actions.extend([
            "Maintain strict blood pressure and glucose control.",
            "Follow a DASH/Mediterranean-style diet and reduce sodium.",
            "Exercise regularly and avoid prolonged sedentary periods.",
            "Know FAST stroke warning signs (Face, Arm, Speech, Time)."
        ])
        if patient_data.get('smoking_status') in (2, 3):
            actions.append("Quit smoking to reduce near-term and long-term stroke risk.")
        return actions
    
    # ===================== HELPER METHODS =====================
    
    def _generate_header(self, report_title):
        """Generate report header"""
        header = f"""
{sep}
                        {self.PLATFORM_NAME}
                    PROFESSIONAL HEALTH ASSESSMENT REPORT
{sep}

Report Type:        {report_title}
Report Date:        {self.report_date}
Report ID:          HC-{datetime.now().strftime('%Y%m%d%H%M%S')}

{sep}

"""
        return header
    
    def _generate_patient_section(self, patient_data):
        """Generate patient information section"""
        section = f"""
      PATIENT INFORMATION
      {sep}

      """
        if 'name' in patient_data:
            section += f"Patient Name:              {patient_data['name']}\n"
        if 'age' in patient_data:
            section += f"Age:                       {patient_data['age']} years\n"
        if 'gender' in patient_data:
            section += f"Gender:                    {patient_data['gender']}\n"
        
        section += f"""
Report Generated By:       Health Companion AI Platform
Platform:                  health-companion.local
Assessment Method:         Machine Learning-based Risk Analysis

{sep}

"""
        return section
    
    def _generate_cardiovascular_inputs(self, patient_data):
        """Generate cardiovascular input summary"""
        section = """
PROVIDED HEALTH INFORMATION
{sep}

Physical Measurements:
  • Height:                 {height} cm
  • Weight:                 {weight} kg
  • Age:                    {age} years
  • Gender:                 {gender}

Blood Pressure & Cardiovascular:
  • Systolic BP:            {systolic_bp} mmHg
  • Diastolic BP:           {diastolic_bp} mmHg
  • Cholesterol Level:      {cholesterol_desc}
  • Glucose Level:          {glucose_desc}

Lifestyle Factors:
  • Smoking Status:         {smoking}
  • Alcohol Consumption:    {alcohol}
  • Physical Activity:      {activity}

{sep}

""".format(
            height=patient_data.get('height', 'N/A'),
            weight=patient_data.get('weight', 'N/A'),
            age=patient_data.get('age', 'N/A'),
            gender=patient_data.get('gender', 'N/A'),
            systolic_bp=patient_data.get('systolic_bp', 'N/A'),
            diastolic_bp=patient_data.get('diastolic_bp', 'N/A'),
            cholesterol_desc=self._decode_cholesterol(patient_data.get('cholesterol', 1)),
            glucose_desc=self._decode_glucose(patient_data.get('glucose', 1)),
            smoking='Yes - Current Smoker' if patient_data.get('smoking') == 1 else 'No - Non-smoker',
            alcohol='Yes' if patient_data.get('alcohol') == 1 else 'No',
            activity='Yes - Physically Active' if patient_data.get('physical_activity') == 1 else 'No - Sedentary',
            sep='='*80
          )
        return section
    
    def _generate_diabetes_inputs(self, patient_data):
        """Generate diabetes input summary"""
        section = """
PROVIDED HEALTH INFORMATION
{sep}

Demographics:
  • Age:                    {age} years
  • Gender:                 {gender}
  • Pregnancy History:      {pregnancies} pregnancies

Physical Measurements:
  • Height:                 {height} cm
  • Weight:                 {weight} kg
  • Fasting Glucose:        {glucose} mg/dL
  • Blood Pressure:         {blood_pressure} mmHg

Metabolic Markers:
  • Insulin Level:          {insulin} µU/ml
  • Skin Fold Thickness:    {skin_thickness} mm
  • Diabetes Pedigree:      {dpf} (family history score)

{sep}

""".format(
            age=patient_data.get('age', 'N/A'),
            gender=patient_data.get('gender', 'N/A'),
            pregnancies=patient_data.get('pregnancies', 'N/A'),
            height=patient_data.get('height', 'N/A'),
            weight=patient_data.get('weight', 'N/A'),
            glucose=patient_data.get('glucose', 'N/A'),
            blood_pressure=patient_data.get('blood_pressure', 'N/A'),
            insulin=patient_data.get('insulin', 'N/A'),
            skin_thickness=patient_data.get('skin_thickness', 'N/A'),
            dpf=patient_data.get('diabetes_pedigree_function', 'N/A'),
            sep='='*80
          )
        return section
    
    def _generate_stroke_inputs(self, patient_data):
        """Generate stroke input summary"""
        section = """
PROVIDED HEALTH INFORMATION
{sep}

Demographics:
  • Age:                    {age} years
  • Gender:                 {gender}
  • Marital Status:         {marital}
  • Work Type:              {work_type}
  • Residence Type:         {residence}

Medical History:
  • Hypertension:           {hypertension}
  • Heart Disease:          {heart_disease}

Physical & Metabolic:
  • Height:                 {height} cm
  • Weight:                 {weight} kg
  • Average Glucose:        {glucose} mg/dL

Lifestyle Factors:
  • Smoking Status:         {smoking}

{sep}

""".format(
            age=patient_data.get('age', 'N/A'),
            gender=patient_data.get('gender', 'N/A'),
            marital='Married' if patient_data.get('ever_married') == 1 else 'Single/Never Married',
            work_type=patient_data.get('work_type', 'N/A'),
            residence='Urban' if patient_data.get('residence_type') == 1 else 'Rural',
            hypertension='Yes' if patient_data.get('hypertension') == 1 else 'No',
            heart_disease='Yes' if patient_data.get('heart_disease') == 1 else 'No',
            height=patient_data.get('height', 'N/A'),
            weight=patient_data.get('weight', 'N/A'),
            glucose=patient_data.get('avg_glucose', 'N/A'),
      smoking=self._decode_smoking_status(patient_data.get('smoking_status', 0)),
      sep='='*80
    )
        return section
    
    def _generate_cardiovascular_metrics(self, patient_data):
        """Generate cardiovascular calculated metrics"""
        section = """
CALCULATED HEALTH METRICS
{sep}

BODY MASS INDEX (BMI) ASSESSMENT:
  • BMI Value:              {bmi:.1f} kg/m²
  • Classification:         {bmi_category}
  • Status:                 {bmi_status}

BLOOD PRESSURE CLASSIFICATION:
  • Systolic/Diastolic:     {systolic_bp}/{diastolic_bp} mmHg
  • BP Category:            {bp_category}
  • Clinical Significance:  {bp_significance}

METABOLIC MARKERS:
  • Cholesterol:            {cholesterol_category}
  • Glucose Level:          {glucose_category}

AGE ASSESSMENT:
  • Age Group:              {age_group}

{sep}

""".format(
            bmi=patient_data.get('bmi', 0),
            bmi_category=patient_data.get('bmi_category', 'N/A'),
            bmi_status=self._get_bmi_status(patient_data.get('bmi_category', '')),
            systolic_bp=patient_data.get('systolic_bp', 'N/A'),
            diastolic_bp=patient_data.get('diastolic_bp', 'N/A'),
            bp_category=patient_data.get('bp_category', 'N/A'),
            bp_significance=self._get_bp_significance(patient_data.get('bp_category', '')),
            cholesterol_category=self._decode_cholesterol(patient_data.get('cholesterol', 1)),
            glucose_category=self._decode_glucose(patient_data.get('glucose', 1)),
            age_group=self._get_age_group(patient_data.get('age', 0)),
            sep='='*80
          )
        return section
    
    def _generate_diabetes_metrics(self, patient_data):
        """Generate diabetes calculated metrics"""
        section = """
CALCULATED HEALTH METRICS
{sep}

BODY MASS INDEX (BMI) ASSESSMENT:
  • BMI Value:              {bmi:.1f} kg/m²
  • Classification:         {bmi_category}
  • Health Status:          {bmi_status}

GLUCOSE METABOLISM:
  • Fasting Glucose:        {glucose} mg/dL
  • Glucose Status:         {glucose_status}
  • Reference Range:        70-100 mg/dL (Normal fasting)

INSULIN SENSITIVITY:
  • Insulin Level:          {insulin} µU/ml
  • Interpretation:         {insulin_status}

RISK FACTORS SUMMARY:
  • Family History Score:   {dpf:.3f}
  • Age Group:              {age_group}

{sep}

""".format(
            bmi=patient_data.get('bmi', 0),
            bmi_category=patient_data.get('bmi_category', 'N/A'),
            bmi_status=self._get_bmi_status(patient_data.get('bmi_category', '')),
            glucose=patient_data.get('glucose', 'N/A'),
            glucose_status=self._get_glucose_status(patient_data.get('glucose', 0)),
            insulin=patient_data.get('insulin', 'N/A'),
            insulin_status=self._get_insulin_status(patient_data.get('insulin', 0)),
            dpf=patient_data.get('diabetes_pedigree_function', 0),
            age_group=self._get_age_group(patient_data.get('age', 0)),
            sep='='*80
          )
        return section
    
    def _generate_stroke_metrics(self, patient_data):
        """Generate stroke calculated metrics"""
        section = """
CALCULATED HEALTH METRICS
{sep}

BODY MASS INDEX (BMI) ASSESSMENT:
  • BMI Value:              {bmi:.1f} kg/m²
  • Classification:         {bmi_category}
  • Health Status:          {bmi_status}

GLUCOSE METABOLISM:
  • Average Glucose:        {glucose} mg/dL
  • Glucose Status:         {glucose_status}

CARDIOVASCULAR RISK FACTORS:
  • Hypertension Status:    {hypertension}
  • Heart Disease History:  {heart_disease}
  • Combined CVD Risk:      {cvd_risk}

DEMOGRAPHIC RISK:
  • Age Group:              {age_group}
  • Age Risk Assessment:    {age_risk}

{sep}

""".format(
            bmi=patient_data.get('bmi', 0),
            bmi_category=patient_data.get('bmi_category', 'N/A'),
            bmi_status=self._get_bmi_status(patient_data.get('bmi_category', '')),
            glucose=patient_data.get('avg_glucose', 'N/A'),
            glucose_status=self._get_glucose_status(patient_data.get('avg_glucose', 0)),
            hypertension='Present (Elevated Risk)' if patient_data.get('hypertension') == 1 else 'Absent (Lower Risk)',
            heart_disease='Present (Elevated Risk)' if patient_data.get('heart_disease') == 1 else 'Absent (Lower Risk)',
            cvd_risk='Very High' if (patient_data.get('hypertension') == 1 and patient_data.get('heart_disease') == 1) else 'Moderate to High' if (patient_data.get('hypertension') == 1 or patient_data.get('heart_disease') == 1) else 'Normal',
            age_group=self._get_age_group(patient_data.get('age', 0)),
            age_risk='High (Age > 50)' if patient_data.get('age', 0) > 50 else 'Moderate (Age 30-50)' if patient_data.get('age', 0) >= 30 else 'Lower (Age < 30)',
            sep='='*80
          )
        return section
    
    def _generate_risk_analysis(self, risk_prediction):
        """Generate risk analysis section"""
        risk_level = risk_prediction.get('risk_level', 'Unknown')
        probability = risk_prediction.get('probability', 0)
        
        # Determine visual indicator
        if probability > 0.7:
            risk_indicator = "*** HIGH RISK ***"
        elif probability > 0.4:
            risk_indicator = "** MODERATE RISK **"
        else:
            risk_indicator = "* LOW RISK *"
        
        section = f"""
RISK PREDICTION & ANALYSIS
{sep}

ASSESSMENT RESULT:

  Risk Level:               {risk_indicator}
  Risk Category:            {risk_level}
  Probability Score:        {probability*100:.1f}%
  Confidence Level:         High (Based on ML Model)

INTERPRETATION:
  This assessment indicates a {risk_level.lower()} for disease development based on
  the provided health parameters and advanced machine learning analysis.

{sep}

"""
        return section
    
    def _generate_cardiovascular_interpretation(self, patient_data, risk_prediction):
        """Generate cardiovascular interpretation section"""
        risk_level = risk_prediction.get('risk_level', 'Unknown')
        probability = risk_prediction.get('probability', 0)
        
        section = f"""
CLINICAL INTERPRETATION
{sep}

CARDIOVASCULAR HEALTH SUMMARY:

Based on the comprehensive analysis of your health data, the following observations
are noted:

"""
        
        # BMI assessment
        bmi_cat = patient_data.get('bmi_category', '').lower()
        if 'obese' in bmi_cat:
            section += """
1. BODY COMPOSITION: Your BMI indicates obesity, which is a significant risk factor
   for cardiovascular disease. Weight reduction through lifestyle modifications is
   strongly recommended.

"""
        elif 'overweight' in bmi_cat:
            section += """
1. BODY COMPOSITION: Your BMI indicates overweight status. Gradual weight reduction
   through diet and exercise is recommended to reduce cardiovascular risk.

"""
        else:
            section += """
1. BODY COMPOSITION: Your BMI is within a healthy range, which is favorable for
   cardiovascular health.

"""
        
        # Blood pressure assessment
        bp_cat = patient_data.get('bp_category', '').lower()
        if 'stage 2' in bp_cat:
            section += """
2. BLOOD PRESSURE: Your blood pressure reading is elevated (Stage 2 Hypertension).
   This is a major risk factor for heart disease and stroke. Immediate medical
   consultation and intervention are strongly recommended.

"""
        elif 'stage 1' in bp_cat:
            section += """
2. BLOOD PRESSURE: Your blood pressure is in Stage 1 Hypertension range. Medical
   evaluation and possible treatment should be considered.

"""
        elif 'elevated' in bp_cat:
            section += """
2. BLOOD PRESSURE: Your blood pressure is slightly elevated. Lifestyle modifications
   and regular monitoring are recommended.

"""
        else:
            section += """
2. BLOOD PRESSURE: Your blood pressure is within normal range, which is favorable
   for cardiovascular health.

"""
        
        # Lifestyle factors
        if patient_data.get('smoking') == 1:
            section += """
3. SMOKING: Active smoking significantly increases cardiovascular risk. Smoking
   cessation is critical and should be a priority. Consider consulting a healthcare
   provider for smoking cessation support.

"""
        else:
            section += """
3. SMOKING: You are not a smoker, which is positive for cardiovascular health.

"""
        
        if patient_data.get('alcohol') == 1:
            section += """
4. ALCOHOL: Regular alcohol consumption may increase cardiovascular risk. Moderation
   or abstinence is recommended.

"""
        else:
            section += """
4. ALCOHOL: You report no significant alcohol consumption, which supports
   cardiovascular health.

"""
        
        if patient_data.get('physical_activity') == 0:
            section += """
5. PHYSICAL ACTIVITY: Sedentary lifestyle is a significant risk factor. Regular
   physical activity (at least 150 minutes moderate-intensity per week) is essential.

"""
        else:
            section += """
5. PHYSICAL ACTIVITY: You maintain physical activity, which is protective for
   cardiovascular health.

"""
        
        # Overall risk
        section += f"""
OVERALL CARDIOVASCULAR RISK ASSESSMENT:

Your comprehensive cardiovascular risk profile indicates a {risk_level.lower()} for
developing cardiovascular disease. The AI model estimates a {probability*100:.1f}% probability
of cardiovascular risk based on your current health parameters.

{sep}

"""
        return section
    
    def _generate_diabetes_interpretation(self, patient_data, risk_prediction):
        """Generate diabetes interpretation section"""
        risk_level = risk_prediction.get('risk_level', 'Unknown')
        probability = risk_prediction.get('probability', 0)
        
        section = f"""
CLINICAL INTERPRETATION
{sep}

DIABETES RISK SUMMARY:

Based on comprehensive metabolic and demographic analysis, the following observations
are noted:

"""
        
        # Glucose assessment
        glucose = patient_data.get('glucose', 0)
        if glucose >= 126:
            section += f"""
1. FASTING GLUCOSE: Your fasting glucose level ({glucose} mg/dL) is in the diabetic
   range (≥126 mg/dL). This warrants immediate medical consultation and possible
   diagnostic testing (HbA1c, OGTT) for diabetes confirmation.

"""
        elif glucose >= 100:
            section += f"""
1. FASTING GLUCOSE: Your fasting glucose level ({glucose} mg/dL) indicates impaired
   fasting glucose (prediabetes). Lifestyle modifications are urgent to prevent
   progression to type 2 diabetes.

"""
        else:
            section += f"""
1. FASTING GLUCOSE: Your fasting glucose level ({glucose} mg/dL) is within normal range
   (70-99 mg/dL), which is favorable.

"""
        
        # BMI assessment
        bmi_cat = patient_data.get('bmi_category', '').lower()
        if 'obese' in bmi_cat:
            section += """
2. BODY WEIGHT: Obesity significantly increases diabetes risk. Weight loss of 5-10%
   can substantially reduce risk. A structured weight loss program is recommended.

"""
        elif 'overweight' in bmi_cat:
            section += """
2. BODY WEIGHT: Overweight status increases diabetes risk. Gradual weight reduction
   through diet and exercise is strongly recommended.

"""
        else:
            section += """
2. BODY WEIGHT: Your weight is within a healthy range relative to height.

"""
        
        # Insulin assessment
        insulin = patient_data.get('insulin', 0)
        if insulin > 0:
            if insulin > 12:
                section += f"""
3. INSULIN LEVEL: Your insulin level ({insulin} µU/ml) suggests possible insulin
   resistance, a key risk factor for type 2 diabetes. Further evaluation by an
   endocrinologist is recommended.

"""
            else:
                section += f"""
3. INSULIN LEVEL: Your insulin level ({insulin} µU/ml) is within normal range.

"""
        
        # Family history
        dpf = patient_data.get('diabetes_pedigree_function', 0)
        if dpf > 0.8:
            section += f"""
4. FAMILY HISTORY: Strong family history of diabetes (score: {dpf:.3f}) significantly
   increases your genetic risk. Enhanced prevention strategies are essential.

"""
        else:
            section += f"""
4. FAMILY HISTORY: Family history assessment (score: {dpf:.3f}) shows moderate to
   low genetic predisposition to diabetes.

"""
        
        # Age assessment
        age = patient_data.get('age', 0)
        if age > 45:
            section += """
5. AGE FACTOR: Age over 45 is associated with increased diabetes risk. Regular
   screening is recommended.

"""
        
        # Overall risk
        section += f"""
OVERALL DIABETES RISK ASSESSMENT:

Your metabolic profile indicates a {risk_level.lower()} for developing type 2 diabetes.
The AI model estimates a {probability*100:.1f}% probability based on your glucose levels,
BMI, insulin levels, and family history.

{sep}

"""
        return section
    
    def _generate_stroke_interpretation(self, patient_data, risk_prediction):
        """Generate stroke interpretation section"""
        risk_level = risk_prediction.get('risk_level', 'Unknown')
        probability = risk_prediction.get('probability', 0)
        
        section = f"""
CLINICAL INTERPRETATION
{sep}

STROKE RISK SUMMARY:

Based on demographic, medical history, and metabolic factors, the following
observations are noted:

"""
        
        # Cardiovascular history
        if patient_data.get('hypertension') == 1:
            section += """
1. HYPERTENSION: You have a history of high blood pressure, a major stroke risk factor.
   Blood pressure control with medication and lifestyle changes is critical.

"""
        else:
            section += """
1. HYPERTENSION: No history of hypertension reported, which is favorable.

"""
        
        if patient_data.get('heart_disease') == 1:
            section += """
2. HEART DISEASE: You have a history of cardiac disease. This significantly increases
   stroke risk. Close cardiology follow-up is essential.

"""
        else:
            section += """
2. HEART DISEASE: No history of heart disease reported.

"""
        
        # Age assessment
        age = patient_data.get('age', 0)
        if age > 60:
            section += f"""
3. AGE: At age {age}, stroke risk increases significantly. Regular health screening
   and preventive care are essential.

"""
        elif age > 50:
            section += f"""
3. AGE: At age {age}, you are in a higher-risk age group for stroke. Regular
   monitoring is recommended.

"""
        else:
            section += f"""
3. AGE: At age {age}, you are relatively younger, which is favorable for stroke
   prevention.

"""
        
        # Glucose assessment
        glucose = patient_data.get('avg_glucose', 0)
        if glucose > 200:
            section += f"""
4. GLUCOSE LEVEL: Average glucose of {glucose} mg/dL is elevated and suggests
   possible diabetes or poor glycemic control. This increases stroke risk.

"""
        elif glucose > 125:
            section += f"""
4. GLUCOSE LEVEL: Average glucose of {glucose} mg/dL indicates impaired glucose
   tolerance. Better glycemic control is needed.

"""
        else:
            section += f"""
4. GLUCOSE LEVEL: Average glucose level ({glucose} mg/dL) is within acceptable range.

"""
        
        # BMI assessment
        bmi_cat = patient_data.get('bmi_category', '').lower()
        if 'obese' in bmi_cat:
            section += """
5. BODY WEIGHT: Obesity increases stroke risk through multiple mechanisms. Weight
   reduction is a key preventive strategy.

"""
        elif 'overweight' in bmi_cat:
            section += """
5. BODY WEIGHT: Overweight status moderately increases stroke risk. Gradual weight
   loss is beneficial.

"""
        else:
            section += """
5. BODY WEIGHT: Body weight is within a healthy range.

"""
        
        # Overall risk
        section += f"""
OVERALL STROKE RISK ASSESSMENT:

Your comprehensive profile indicates a {risk_level.lower()} for stroke. The AI model
estimates a {probability*100:.1f}% probability based on your age, medical history,
glucose levels, and other factors.

{sep}

"""
        return section
    
    def _generate_cardiovascular_recommendations(self, patient_data, risk_prediction):
        """Generate cardiovascular recommendations"""
        risk_level = risk_prediction.get('risk_level', 'Unknown')
        probability = risk_prediction.get('probability', 0)
        
        section = f"""
      PERSONALIZED HEALTH RECOMMENDATIONS
      {sep}

      """
        
        if probability > 0.7:
            section += """
⚠ URGENT RECOMMENDATIONS (High Risk):

  MEDICAL CONSULTATION:
    • Schedule an appointment with a cardiologist immediately
    • Request a comprehensive cardiac evaluation including:
      - ECG (Electrocardiogram)
      - Echocardiogram
      - Stress test (if appropriate)
      - Complete lipid panel
    • Discuss potential medication (statins, beta-blockers, ACE inhibitors)

"""
        
        section += """
  DIETARY MODIFICATIONS:
    ✓ Adopt a heart-healthy diet:
      - Reduce saturated fat intake to <7% of daily calories
      - Eliminate trans fats completely
      - Increase soluble fiber (oats, beans, fruits)
      - Choose lean proteins (fish, poultry, legumes)
      - Limit sodium to <2,300 mg per day
      - Include omega-3 rich foods (salmon, mackerel, walnuts)
      - Increase fruits and vegetables (8-10 servings daily)
      - Use olive oil instead of butter or coconut oil

  PHYSICAL ACTIVITY:
    ✓ Gradually increase activity level:
      - Aim for 150 minutes moderate-intensity aerobic activity weekly
      - Include 2 sessions of resistance training per week
      - Start slowly if sedentary: 15-20 minutes daily
      - Include activities like brisk walking, swimming, cycling
      - Avoid sudden strenuous activity

  LIFESTYLE MODIFICATIONS:
    ✓ Smoking cessation:
      - Quit smoking completely (reduces risk by 50% within one year)
      - Seek professional help or nicotine replacement therapy
    
    ✓ Alcohol management:
      - Limit to moderate amounts (1 drink/day for women, 2 for men)
      - Consider abstinence if risk factors present
    
    ✓ Stress management:
      - Practice relaxation techniques (yoga, meditation, deep breathing)
      - Consider counseling or support groups
      - Aim for 7-9 hours quality sleep nightly
    
    ✓ Regular monitoring:
      - Check blood pressure at least monthly
      - Schedule regular follow-ups with physician
      - Keep track of weight changes

  MEDICATIONS:
    • Take any prescribed cardiovascular medications as directed
    • Do not discontinue medications without physician consultation
    • Report any side effects to your doctor

  FOLLOW-UP SCHEDULE:
    • Initial cardiologist consultation: Within 1-2 weeks
    • Repeat risk assessment: Every 3-6 months
    • Regular check-ups with primary care physician: Every 3 months

{sep}

"""
        return section
    
    def _generate_diabetes_recommendations(self, patient_data, risk_prediction):
        """Generate diabetes recommendations"""
        risk_level = risk_prediction.get('risk_level', 'Unknown')
        probability = risk_prediction.get('probability', 0)
        
        section = f"""
      PERSONALIZED HEALTH RECOMMENDATIONS
      {sep}

      """
        
        if probability > 0.7:
            section += """
⚠ URGENT RECOMMENDATIONS (High Risk):

  MEDICAL CONSULTATION:
    • Schedule an endocrinologist or diabetologist appointment immediately
    • Request comprehensive testing:
      - HbA1c test (glycated hemoglobin)
      - Oral glucose tolerance test (OGTT)
      - Fasting glucose and insulin levels
      - Comprehensive metabolic panel
      - Lipid panel
      - Kidney function and liver function tests
      - Urinalysis and urine albumin
    • Discuss medication options (Metformin is typically first-line)

"""
        
        section += """
  DIETARY MODIFICATIONS:
    ✓ Diabetes-friendly nutrition:
      - Carbohydrate counting and consistency
      - Focus on low glycemic index foods (whole grains, legumes, vegetables)
      - Include lean proteins at every meal
      - Limit refined sugars and processed foods
      - Choose complex carbohydrates (brown rice, whole wheat, oats)
      - Include soluble fiber (beans, lentils, vegetables, fruits)
      - Portion control is critical
      - Spacing meals evenly throughout the day
      - Reduce saturated fats; use healthy oils

  PHYSICAL ACTIVITY:
    ✓ Structured exercise program:
      - Aim for 150 minutes moderate-intensity activity per week
      - Include resistance training 2-3 times weekly
      - Start gradually if inactive (10-15 minutes daily)
      - Activities: brisk walking, jogging, swimming, cycling, strength training
      - Check blood glucose before and after exercise
      - Stay hydrated during physical activity

  WEIGHT MANAGEMENT:
    ✓ Gradual weight reduction:
      - Target: 5-10% weight loss initially
      - Sustainable loss: 1-2 pounds per week
      - Combine diet and exercise
      - Consider referral to dietitian or weight loss program
      - Track food intake and activity

  BLOOD GLUCOSE MONITORING:
    ✓ Home monitoring:
      - Fasting glucose checks (if recommended)
      - Monitor symptoms of hypo- or hyperglycemia
      - Keep log of blood glucose readings
      - Share records with healthcare provider

  LIFESTYLE MODIFICATIONS:
    ✓ Stress and sleep:
      - Manage stress through relaxation techniques
      - Aim for 7-9 hours quality sleep
      - Poor sleep worsens glucose control
    
    ✓ Regular screening:
      - Eye examinations (diabetic retinopathy screening)
      - Foot examinations (neuropathy and ulcer prevention)
      - Kidney function tests
      - Cardiovascular risk assessment

  MEDICATIONS:
    • Take diabetes medications as prescribed
    • Report side effects to healthcare provider
    • Do not modify dose without medical guidance
    • Maintain regular medication refills

  FOLLOW-UP SCHEDULE:
    • Initial endocrinologist visit: Within 1 week
    • HbA1c testing: Every 3 months initially
    • Comprehensive metabolic assessment: Every 6 months
    • Annual comprehensive eye and foot examinations

  EDUCATIONAL SUPPORT:
    • Enroll in diabetes education program
    • Learn to recognize hypoglycemia symptoms
    • Understand medication interactions
    • Develop sick day management plan

{sep}

"""
        return section
    
    def _generate_stroke_recommendations(self, patient_data, risk_prediction):
        """Generate stroke recommendations"""
        risk_level = risk_prediction.get('risk_level', 'Unknown')
        probability = risk_prediction.get('probability', 0)
        
        section = f"""
      PERSONALIZED HEALTH RECOMMENDATIONS
      {sep}

      """
        
        if probability > 0.7:
            section += """
⚠ URGENT RECOMMENDATIONS (High Risk):

  MEDICAL CONSULTATION:
    • Consult neurologist or stroke specialist immediately
    • Request comprehensive vascular assessment:
      - Carotid ultrasound (for carotid stenosis)
      - ECG (cardiac arrhythmias detection)
      - Echocardiogram (cardiac sources of emboli)
      - MRI/CT of brain (baseline structural imaging)
      - Blood coagulation studies
    • Consider antiplatelet therapy (aspirin or clopidogrel)

"""
        
        section += """
  CARDIOVASCULAR HEALTH:
    ✓ Blood pressure management:
      - Target BP: <130/80 mmHg
      - Regular monitoring (home BP cuff)
      - Medication compliance if prescribed
      - Reduce sodium to <2,300 mg daily
      - DASH diet (Dietary Approaches to Stop Hypertension)

    ✓ Cholesterol management:
      - Target LDL: <70 mg/dL (for high-risk patients)
      - Increase HDL cholesterol
      - Reduce triglycerides
      - Statin therapy may be indicated
      - Regular lipid panel monitoring

  DIETARY MODIFICATIONS:
    ✓ Stroke-prevention diet:
      - Mediterranean or DASH diet recommended
      - Increase whole grains, fruits, vegetables
      - Choose omega-3 rich foods (fatty fish 2x weekly)
      - Reduce saturated and trans fats
      - Limit sodium intake
      - Control portion sizes
      - Reduce refined sugars

  PHYSICAL ACTIVITY:
    ✓ Structured cardiovascular exercise:
      - Aim for 150 minutes moderate-intensity weekly
      - Include aerobic activities (walking, swimming, cycling)
      - Resistance training 2 days per week
      - Flexibility exercises and balance training
      - Start gradually if sedentary
      - Avoid sudden strenuous activity

  WEIGHT MANAGEMENT:
    ✓ Maintain healthy BMI:
      - Target BMI: 18.5-24.9 kg/m²
      - If overweight: gradual weight loss
      - Weight loss can reduce stroke risk by 10-20%

  GLUCOSE CONTROL:
    ✓ Glycemic management:
      - If diabetic or prediabetic: strict glucose control
      - Regular glucose monitoring
      - Medication adherence if prescribed
      - Target HbA1c: <7% (or per physician guidance)

  LIFESTYLE MODIFICATIONS:
    ✓ Smoking cessation (CRITICAL):
      - Complete smoking cessation is essential
      - Reduces stroke risk significantly
      - Seek professional cessation programs
      - Consider nicotine replacement therapy
    
    ✓ Alcohol moderation:
      - Limit to moderate amounts
      - Excessive alcohol increases stroke risk
      - Avoid binge drinking

    ✓ Stress and sleep management:
      - Stress reduction (meditation, yoga, counseling)
      - Aim for 7-9 hours quality sleep
      - Sleep apnea screening and treatment if needed
      - Regular relaxation practices

  MEDICATIONS:
    • Antihypertensive medications (if prescribed)
    • Antiplatelet therapy (aspirin, clopidogrel)
    • Anticoagulant therapy (if atrial fibrillation)
    • Statins (cholesterol management)
    • Diabetes medications (if applicable)
    • Take all medications as prescribed
    • Report any side effects

  RECOGNIZE STROKE SYMPTOMS (F.A.S.T.):
    ⚠ FACE: Facial drooping or weakness
    ⚠ ARM: Arm weakness or numbness
    ⚠ SPEECH: Speech difficulty or slurred words
    ⚠ TIME: Call 911 immediately if any symptoms present
    
    Every minute counts in stroke treatment!

  FOLLOW-UP SCHEDULE:
    • Neurology/stroke specialist: Every 3-6 months
    • Primary care physician: Every 1-3 months
    • Annual comprehensive vascular evaluation
    • Regular blood pressure monitoring
    • Annual lipid panel and glucose testing

  MEDICAL ALERT SYSTEM:
    • Consider medical alert bracelet/necklace
    • Inform family, friends, colleagues of stroke risk
    • Provide emergency contacts to household members

{sep}

"""
        return section
    
    def _generate_footer(self):
        """Generate report footer with disclaimer"""
        footer = f"""
PLATFORM INFORMATION
{sep}

This report is generated by the {self.PLATFORM_NAME} platform using artificial intelligence
and machine learning algorithms for health risk stratification. The assessment is based
on statistical models trained on extensive clinical data and established medical
research.

Accuracy Note: The AI model achieves approximately 85-92% accuracy in risk prediction.
This report should be interpreted in the context of clinical judgment and professional
medical evaluation.

{sep}

{self.DISCLAIMER_TEXT}

{sep}

Report Confidentiality:
This report contains sensitive personal health information. It should be handled
confidentially and securely. Share only with authorized healthcare providers.

Date Generated:     {self.report_date}
Platform:           Health Companion AI Health Assessment System
Report Status:      CONFIDENTIAL - For Medical Use Only

{sep}

For questions or concerns about this report, please contact your healthcare provider
or the Health Companion support team.

End of Report

{sep}
"""
        return footer
    
    # ===================== UTILITY METHODS =====================
    
    @staticmethod
    def _decode_cholesterol(level):
        """Decode cholesterol level"""
        if level == 1:
            return "Normal (<200 mg/dL)"
        elif level == 2:
            return "Above Normal (200-239 mg/dL)"
        elif level == 3:
            return "Well Above Normal (≥240 mg/dL)"
        return "Unknown"
    
    @staticmethod
    def _decode_glucose(level):
        """Decode glucose level"""
        if level == 1:
            return "Normal (<100 mg/dL fasting)"
        elif level == 2:
            return "Above Normal (≥100 mg/dL fasting)"
        return "Unknown"
    
    @staticmethod
    def _decode_smoking_status(status):
        """Decode smoking status"""
        statuses = {
            0: "Never smoked",
            1: "Formerly smoked",
            2: "Currently smokes",
            3: "Smokes occasionally"
        }
        return statuses.get(status, "Unknown")
    
    @staticmethod
    def _get_bmi_status(category):
        """Get BMI health status"""
        category_lower = category.lower()
        if 'underweight' in category_lower:
            return "Below healthy weight range"
        elif 'normal' in category_lower:
            return "Healthy weight range"
        elif 'overweight' in category_lower:
            return "Above healthy weight range"
        elif 'obese' in category_lower:
            return "Significantly above healthy weight range"
        return "Unable to assess"
    
    @staticmethod
    def _get_bp_significance(category):
        """Get BP clinical significance"""
        category_lower = category.lower()
        if 'stage 2' in category_lower:
            return "Requires immediate medical intervention"
        elif 'stage 1' in category_lower:
            return "Requires medical evaluation and possible treatment"
        elif 'elevated' in category_lower:
            return "Lifestyle modifications recommended"
        elif 'normal' in category_lower:
            return "Within normal range; continue monitoring"
        return "Requires evaluation"
    
    @staticmethod
    def _get_age_group(age):
        """Get age group classification"""
        if age < 30:
            return "Young (< 30 years)"
        elif age < 40:
            return "Early Middle Age (30-39 years)"
        elif age < 50:
            return "Middle Age (40-49 years)"
        elif age < 60:
            return "Senior (50-59 years)"
        else:
            return "Elderly (≥ 60 years)"
    
    @staticmethod
    def _get_glucose_status(glucose):
        """Get glucose status interpretation"""
        if glucose >= 126:
            return "Diabetic range - Medical evaluation needed"
        elif glucose >= 100:
            return "Impaired fasting glucose (Prediabetic)"
        elif glucose >= 70:
            return "Normal range"
        else:
            return "Low (Hypoglycemic)"
    
    @staticmethod
    def _get_insulin_status(insulin):
        """Get insulin status interpretation"""
        if insulin > 12:
            return "Elevated - Possible insulin resistance"
        elif insulin > 0:
            return "Normal range"
        else:
            return "Not measured or insufficient data"


# Example usage function
def create_sample_cardiovascular_report():
    """Create a sample cardiovascular report for testing"""
    generator = HealthReportGenerator()
    
    patient_data = {
        'name': 'John Doe',
        'age': 55,
        'gender': 'Male',
        'height': 180,
        'weight': 95,
        'bmi': 29.3,
        'bmi_category': 'Overweight',
        'systolic_bp': 145,
        'diastolic_bp': 95,
        'bp_category': 'Stage 1 Hypertension',
        'cholesterol': 3,
        'glucose': 2,
        'smoking': 1,
        'alcohol': 1,
        'physical_activity': 0
    }
    
    risk_prediction = {
        'risk_level': 'High Risk',
        'probability': 0.78,
        'recommendation': 'Immediate medical consultation recommended'
    }
    
    return generator.generate_cardiovascular_report(patient_data, risk_prediction)


if __name__ == "__main__":
    # Generate sample report
    report = create_sample_cardiovascular_report()
    print(report)
